// utils/country-iso-mapper.ts
export const iso2CodesByCountry: Record<string, string> = {
  'algeria': 'DZ',
  'angola': 'AO',
  'benin': 'BJ',
  'botswana': 'BW',
  'burkina faso': 'BF',
  'burundi': 'BI',
  'cabo verde': 'CV',
  'cape verde': 'CV',
  'cameroon': 'CM',
  'central african republic': 'CF',
  'chad': 'TD',
  'comoros': 'KM',
  'congo': 'CG',
  'congo, democratic republic of congo': 'CD',
  'democratic republic of congo': 'CD',
  "cote d'ivoire": 'CI',
  'djibouti': 'DJ',
  'egypt': 'EG',
  'equatorial guinea': 'GQ',
  'eritrea': 'ER',
  'eswatini': 'SZ',
  'ethiopia': 'ET',
  'gabon': 'GA',
  'gambia': 'GM',
  'ghana': 'GH',
  'guinea': 'GN',
  'guinea bissau': 'GW',
  'kenya': 'KE',
  'lesotho': 'LS',
  'liberia': 'LR',
  'libya': 'LY',
  'madagascar': 'MG',
  'malawi': 'MW',
  'mali': 'ML',
  'mauritania': 'MR',
  'mauritius': 'MU',
  'morocco': 'MA',
  'mozambique': 'MZ',
  'namibia': 'NA',
  'niger': 'NE',
  'nigeria': 'NG',
  'rwanda': 'RW',
  'sao tome & principe': 'ST',
  'sao tome and principe': 'ST',
  'senegal': 'SN',
  'seychelles': 'SC',
  'sierra leone': 'SL',
  'somalia': 'SO',
  'south africa': 'ZA',
  'south sudan': 'SS',
  'sudan': 'SD',
  'tanzania': 'TZ',
  'togo': 'TG',
  'tunisia': 'TN',
  'uganda': 'UG',
  'zambia': 'ZM',
  'zimbabwe': 'ZW',
  // 'sahrawi arab democratic republic': 'EH',
  'sahrawi republic': 'EH',
};
